server.port=8085
spring.application.name=vetnova_envio

spring.datasource.url=jdbc:h2:file:./data/enviodb;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.ventas-service-url=http://localhost:8084
app.inventario-service-url=http://localhost:8083
app.notificaciones-service-url=http://localhost:8092
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %5level [${spring.application.name}] %logger{25} : %msg%n
